version: "3"
services: 
  rabbitmq:
    image: rabbitmq:3-management
    ports: 
      - 15672:15672
      - 5672:5672
  secure-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15673:15672
      - 5673:5672
    environment: 
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq